### ISSUE TITLE
Support prop updating

### ISSUE THREAD

**Issue by kentcdodds** [sunesimonsen/react-dom-testing#2]
I'd love it if this could support updating props of a component as this is something I have to do manually a fair amount. Something like:

```javascript
const Number = (props) => <div>{props.num}</div>
const {updateProps, div} = mount(<Number num={0} />)
updateProps({num: 1})
```

**Comment by sunesimonsen** [comment]
I haven't really looked into testing these property transitions, what would an `updateProps` do? Would it be at all possible to make it a separate function that either take the component or the DOM node as argument?

**Comment by kentcdodds** [comment]
Ok, after researching it a bit, this is the simplest I could come up with. The root element that's rendered _must_ be a class component so you can get an instance to update the state.

```javascript
import React from 'react'
import ReactDOM from 'react-dom'

class PropUpdater extends React.Component {
  state = {props: this.props.initialProps}
  updateProps = newProps => this.setState({props: newProps})
  render() {
    return React.cloneElement(this.props.children, this.state.props)
  }
}

function renderUpdateable(ui) {
  const div = document.createElement('div')
  const {updateProps} = ReactDOM.render(<PropUpdater>{ui}</PropUpdater>, div)
  return {updateProps, node: div.firstChild}
}

test('works', () => {
  const Number = props => <div>{props.num}</div>
  const {updateProps, node} = renderUpdateable(<Number num={1} />)
  console.log(node.outerHTML) // <div>1</div>
  updateProps({num: 2})
  console.log(node.outerHTML) // <div>2</div>
})
```

# Actually...

Ok, I did a little bit more working and I'm pretty sure this is simpler and doesn't sacrifice anything:

```javascript
import React from 'react'
import ReactDOM from 'react-dom'

function renderUpdateable(ui) {
  const div = document.createElement('div')
  const updateProps = props =>
    ReactDOM.render(React.cloneElement(ui, props), div)
  updateProps() // initial render
  return {updateProps, node: div.firstChild}
}

test('works', () => {
  const Number = props => <div>{props.num}</div>
  const {updateProps, node} = renderUpdateable(<Number num={1} />)
  console.log(node.outerHTML) // <div>1</div>
  updateProps({num: 2})
  console.log(node.outerHTML) // <div>2</div>
})
```

Alternatively, we could monkey-patch a method on the root DOM node so we don't have to have a separate method. I'm not certain how I feel about this though:

```javascript
import React from 'react'
import ReactDOM from 'react-dom'

function render(ui) {
  const div = document.createElement('div')
  const updateProps = props =>
    ReactDOM.render(React.cloneElement(ui, props), div)
  updateProps() // initial render
  return Object.assign(div.firstChild, {updateProps})
}

test('works', () => {
  const Number = props => <div>{props.num}</div>
  const node = render(<Number num={1} />)
  console.log(node.outerHTML) // <div>1</div>
  node.updateProps({num: 2})
  console.log(node.outerHTML) // <div>2</div>
})
```

I'm pretty good with the last two solutions I think. Maybe I'll ask twitter's opinion though...

**Comment by sunesimonsen** [comment]
Hmm thanks for the research, but I don't think this will something I would pursue. I have never really run into a case where I would like to test a prop change like this without `setState` is involved. In that case I would try to trigger the change by simulating an event or fire a Redux action.

**Comment by kentcdodds** [comment]
Ok, that's fine. I think it's clear that your goals for this library are different from my own, so I'll go ahead and make my own :)

Cheers!

**Comment by sunesimonsen** [comment]
@kentcdodds 👍 - thanks for the help.
