### ISSUE TITLE
Support simpler querying?

### ISSUE THREAD

**Issue by kentcdodds** [sunesimonsen/react-dom-testing#3]
One of the things I wanted to do with my library is to promote good practices. I'd love to pull basically all of [this](
https://github.com/kentcdodds/testing-workshop/blob/2ccc2caa1a3146dcc6c981e095eb438fa4650c91/client/test/client-test-utils.js#L17-L33) into this library:

```javascript
function sel(id) {
  return `[data-test="${id}"]`
}

function queryDivByTestId(div, id) {
  return div.querySelector(sel(id))
}

function render(ui) {
  const div = document.createElement('div')
  ReactDOM.render(ui, div)
  return {
    div,
    root: div.children[0],
    queryByTestId: queryDivByTestId.bind(null, div),
  }
}
```

Otherwise, I may build my own (which is fine, that's not a threat, I understand if you'd rather not expand the scope of this).

**Comment by sunesimonsen** [comment]
I'm sorry, but I would really like the mount function to just mount the element and return the mounted node. I think it is a bit confusing getting an extra div I didn't ask for. I would like any utility methods like the `queryByTestId` to be exported separately and take a node as the argument. We might have a bit different use-cases as I'm basically planing to use unexpected-dom on top of this library.

**Comment by kentcdodds** [comment]
Yep, that's fine :+1:

**Comment by sunesimonsen** [comment]
As cool as it would be that my lib would be used from your workshop, I think it might be easier and more pragmatic for you to create a dedicated thing. Thanks a lot for the help.

**Comment by kentcdodds** [comment]
What I want isn't just for my workshop but for all the apps I build and I want to encourage everyone to use it because it has utilities that encourage better testing practices, which is why I want a `queryByTestId` function.

It's fine if you'd prefer this lib to be less opinionated. I just wanted to make sure that I was clear :)

**Comment by kentcdodds** [comment]
Closing due to the same reason mentioned here: https://github.com/sunesimonsen/react-dom-testing/issues/2#issuecomment-373954572
