### ISSUE TITLE
Components that cannot be hosted by a div return errors

### ISSUE THREAD

**Issue by alexjeffburke** [sunesimonsen/react-dom-testing#6]
An interesting case came up recently where we had micro-componentisation of a table component resulting in the header and body components that return semantic elements `<thead>` and `<tbody>` at the top level of their render methods. If `mount()`ed inside a DIV react will throw errors reporting an element layering violation.

The solution we want for in this case was to expand the mount method so the root tag could be overridden if need be. The resulting function looks something like:
```
export function mount(element, tagName = "div") {
  const div = document.createElement(tagName);
  ReactDom.render(element, div);
  return div.firstChild;
}
```

We addressed this in local wrappers when it came up but I think something like that would translate well to `react-dom-testing`. Am opening this issue so we don't forget the case.

**Comment by sunesimonsen** [comment]
You can fix that the following way, which is pretty straightforward:

```js
const component = mount(
  <table>
    <MyFancyHeader>
      <td>USD</td>
      <td>DDK</td>
    </MyFancyHeader>
  </table>
)
```

We might want to document that problem in a recipe.

**Comment by sunesimonsen** [comment]
I added a story for adding a recipe.
